# Generated by Django 3.1.5 on 2021-02-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Photo',
            field=models.ImageField(default=0, upload_to='media/'),
        ),
    ]
