# Generated by Django 3.1.5 on 2021-02-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Confirmnewpassword',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AddField(
            model_name='user',
            name='Newpassword',
            field=models.CharField(default=0, max_length=8),
        ),
    ]
