# Generated by Django 3.1.5 on 2021-02-09 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210209_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Confirmnewpassword',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Newpassword',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Status',
        ),
    ]
